### ISSUE TITLE
Move server to use express

### ISSUE THREAD

**Issue by freiksenet** [apollographql/launchpad#20]
Currently Launchpad server is running as a webtask. It is possible to run it locally with `wt serve` through `wt-cli` library, but it's limited in many ways and doesn't automatically reload. Deploying actual server on webtask means we also need to bundle all files with webtask. It makes sense to move the server to just use express.

# Tasks

* [ ] Reimplement server as normal express server, using [GraphQL Server](http://dev.apollodata.com/tools/graphql-server/index.html)
* [ ] Modify build process to use babel-node in development and compile in production
* [ ] Deploy server code somewhere
* [ ] Make sure built server code is not deployed to netlify
