### ISSUE TITLE
Select npm version of imports

### ISSUE THREAD

**Issue by freiksenet** [apollographql/launchpad#24]
Currenty imports are automatically detected from the code and, if they are new, the latest version of package is selected. After that version is pinned and stays the one that was the latest at the moment of first deploy. Sometimes one wants to be able to update the version or choose a particular version of the package. The interface should be implemented to allow this.

Note that we want to keep automatic dependency detection in place. In addition, any non-standard javascript syntax (such as specifying a version in import) is not a desired solution.

# Tasks

* [ ] Add a query root to server that will return all available versions
* [ ] Allow passing version with a dependency to all mutations that accept dependencies as list of strings (still allow passing dependencies as just strings for auto-latest detection)
* [ ] Implement UI for selecting dependencies (using current modal is fine)

**Comment by brunolemos** [comment]
Much needed

**Comment by brunolemos** [comment]
Is there any workaround for this today?
I tried creating a New launchpad but it used the old version too.
