### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by freiksenet** [apollographql/launchpad#27]
Currently we handle errors from server in pretty simplistic way - we console log them and try to restore to some-kind-of stable state. The latter part is particularly fragile and I've been able to get launchpad in a inconsistent state where it isn't actually saved or deployed. #25 is somewhat related.

Ideally we should:

* Communicate server errors to user
* Allow repeating failed actions (like re-deploying)
* Possibly handle network/server outages gracefully

# Tasks

* [ ] Make sure state is restored in case of errors
* [ ] Communicate failed state to the user
* [ ] Allow repeating failable actions (eg draft deployments)
* [ ] (Bigger) Make Launchpad partially offline-capable, eg queue deploys and save code in local storage
