### ISSUE TITLE
More tests

### ISSUE THREAD

**Issue by freiksenet** [apollographql/launchpad#28]
Currently, test coverage tests most UI components via snapshots of either full or shallow render and tests certain component interactions through enzyme. On server, PadModel is tested with a mock Webtask. Not all functionality is testing and in particular interaction tests are missing.

# Tasks

* [ ] (server) Test whole server with http (partially dependant on #20 
* [ ] (server) Test UserModel and permissions
* [ ] (server) Somehow test WebtaskProvider
* [ ] (client) Test containers with mock Apollo Client.
* [ ] (client) Test editor and graphiql interactions
* [ ] (client) Add high level interaction tests

**Comment by freiksenet** [comment]
Partially done with #46
